### ISSUE TITLE
migration + import

### ISSUE THREAD

**Issue by atherdon** [ChickenKyiv/api-extended-database-Khyati#18]
Some information about migrations:
**first part**
it's a simple thing, you just need to call automigrate and specify tables that you need to drop.
and you need to run that script from CLI

**second part** is complex and related to importing data from js array into db row.

will be to create a file/files, with arrays(you can grab that data from db.json file)
then you'll need to create a file where you'll actually import data from array into db.
as before - you should check the latest version at search-api - and see how i did it here.
btw, i think your issue related to something else, so i'm cloning your repo and will take a look right now

**Comment by atherdon** [comment]
does automigrate script works fine?

**Comment by khyati0212** [comment]
yup

**Comment by atherdon** [comment]
reviewing it

**Comment by atherdon** [comment]
i didn't see files, related to import from models
`let Campground = require(path.resolve(__dirname, 'campground'));


// @TODO remove this include and just find all recipes, stored at database.
let Container    = require(path.resolve(__dirname, 'container'));
let Customer= require(path.resolve(__dirname, 'customer'));
// console.log(  )

let Reservation  = require(path.resolve(__dirname, 'reservation'));
`

But this files are not at bin folder. maybe you didn't commit them?
