### ISSUE TITLE
Jest package - testing

### ISSUE THREAD

**Issue by atherdon** [ChickenKyiv/api-extended-database-Khyati#19]
I think if we'll start this task in parallel with working on import script - we'll be able to save some of your time.

here some links to read/explore
https://medium.com/@ansertechgeek/migrating-from-mocha-to-jest-in-nodejs-app-8afdfa4032d1
https://www.npmjs.com/package/jest-preset-loopback
https://www.npmjs.com/package/@gigster/module-loopback-jest
https://hackernoon.com/api-testing-with-jest-d1ab74005c0a

**Comment by khyati0212** [comment]
sure. I will finish both soon. I am working on them right now

**Comment by khyati0212** [comment]
@atherdon as everyone is giving updates i thought i should do too.. i finished mocha testing.. after that tried using jest but got stuck as i don't know ES6.. So working on it..

**Comment by atherdon** [comment]
not a problem. i don't know es6 eather :)
let think about this. i assume that if proper guidance - you'll be able to
master es6 faster. do you want me to setup for you another repo with
step-by-step tutorial?


On 26-Apr-2018 at 06:05 AM, Khyati wrote:


@atherdon <https://github.com/atherdon> as everyone is giving updates i
thought i should do too.. i finished mocha testing.. after that tried using
jest but got stuck as i don't know ES6.. So working on it..

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ChickenKyiv/api-extended-database/issues/19#issuecomment-384523799>,
or mute the thread

**Comment by khyati0212** [comment]
Cn we do that? It would be really helpful. As I will be able to practice on something kind of real..

**Comment by atherdon** [comment]
@khyati0212 yes, we can. will grab some meal and create that thing for 
you

**Comment by khyati0212** [comment]
Sure. Sounds good.
